use_frameworks!

target 'GTChatKit_Example' do
  pod 'GTChatKit', :path => '../'

  target 'GTChatKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
