language: objective-c
osx_image: xcode9.1

cache: cocoapods
podfile: Example/Podfile

before_install:
  - brew bundle check $BREWFILE || brew bundle $BREWFILE || (brew update && brew bundle $BREWFILE)
  - gem install bundler --no-document
  - pod install --project-directory=Example

branches:
  only:
    - master